[package]
name = "taylorsrus/signal"
description = "Signal class, a lightweight alternative to BindableEvents."
version = "1.0.0"
license = "MIT"
authors = ["Joshua Taylor"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
